#!/bin/bash

script_dir=$(dirname $0)

cluster_name="$1"
node_name="$2"

if [ -z "${cluster_name}" ]; then
  echo "usage: nodeos-stop <CLUSTER_NAME> [NODE_NAME]"
  exit 1
fi

if [ -z "${node_name}" ]; then
  folders=( $(ls -1 "${script_dir}/clusters" | egrep "^${cluster_name}\.") )
  if [ "${#folders[@]}" -eq 0 ]; then
    echo "[ERROR][${cluster_name}] The cluster does not exist"
    exit 1
  fi
  for folder in "${folders[@]}"; do
    node_name=${folder#"${cluster_name}."}
    ${script_dir}/nodeos-stop "${cluster_name}" "${node_name}"
  done
else
  nodeos_home="${script_dir}/clusters/${cluster_name}.${node_name}/nodeos"
  nodeos_pid_file="${nodeos_home}/runtime.pid"

  if [ ! -f "${nodeos_pid_file}" ]; then
    echo "[ERROR]: Failed to locate ${nodeos_pid_file}"
    exit 1
  fi

  pid=$(cat "${nodeos_pid_file}")
  echo "[INFO ][${cluster_name}/${node_name}] Killing the process [${pid}]..."
  kill ${pid}
  while true; do
    proc=$(ps -o pid= -p ${pid})
    [ -z "${proc}" ] && break
    echo -ne "."
    sleep 1
  done

  rm -f "${nodeos_pid_file}"
  echo -ne "\r[INFO ][${cluster_name}/${node_name}] Stopped the node successfully\n"
fi

