#!/bin/bash

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

script_dir=$(dirname $0)

cluster_name="$1"
node_name="$2"

if [ -z "${cluster_name}" ]; then
  echo "usage: nodeos-start <CLUSTER_NAME> [NODE_NAME] [...OPTIONS]"
  exit 1
fi

if [ -z "${node_name}" ] || [[ "${node_name}" =~ ^-.* ]]; then
  shift 1
  folders=( $(ls -1 "${script_dir}/clusters" | egrep "^${cluster_name}\.") )
  if [ "${#folders[@]}" -eq 0 ]; then
    echo "[ERROR][${cluster_name}] The cluster does not exist"
    exit 1
  fi
  for folder in "${folders[@]}"; do
    node_name=${folder#"${cluster_name}."}
    ${script_dir}/nodeos-start "${cluster_name}" "${node_name}" $@
  done
else
  shift 2
  nodeos_home=$(realpath "${script_dir}/clusters/${cluster_name}.${node_name}/nodeos")
  nodeos_config_dir="${nodeos_home}/config"
  nodeos_data_dir="${nodeos_home}/data"

  if [ ! -f "${nodeos_config_dir}/config.ini" ]; then
    echo "[ERROR][${cluster_name}/${node_name}] Failed to locate config.ini under ${nodeos_config_dir}"
    exit 1
  fi

  if [ -f "${nodeos_home}/runtime.pid" ]; then
    pid=$(cat "${nodeos_home}/runtime.pid")
    proc=$(ps -o pid= -p ${pid})
    if [ -n "${proc}" ]; then
      echo "[WARN ][${cluster_name}/${node_name}] Skip starting the node: The node is already running (pid = ${pid})"
      exit
    fi
  fi

  if [ ! -d "${nodeos_data_dir}" ]; then
    mkdir "${nodeos_data_dir}"
  fi

  nodeos \
    --genesis-json "${nodeos_config_dir}/genesis.json" \
    --config-dir "${nodeos_config_dir}" \
    --data-dir "${nodeos_data_dir}" $@ \
    >> "${nodeos_home}/runtime.log" 2>&1 &
  pid=$!
  echo ${pid} > "${nodeos_home}/runtime.pid"
  echo "[INFO ][${cluster_name}/${node_name}] Started the node (pid = ${pid}) successfully"
fi

